// Word pairs: [word A, word B]. Which one goes to the civils is decided at random each game.
(function (root) {
  const WORDS = [
    // Bouffe
    ['Raclette', 'Fondue'],
    ['Tacos', 'Kebab'],
    ['Crêpe', 'Gaufre'],
    ['Ketchup', 'Mayonnaise'],
    ['Croissant', 'Pain au chocolat'],
    ['Macaron', 'Éclair'],
    ['Burger', 'Hot-dog'],
    ['Frites', 'Potatoes'],
    ['Carbonara', 'Bolognaise'],
    ['Sushi', 'Poké bowl'],
    ['Kinder Bueno', 'Twix'],
    ['Pringles', 'Doritos'],
    ['Houmous', 'Guacamole'],
    ['Brunch', 'Goûter'],
    ['Camembert', 'Brie'],
    ['Barbecue', 'Plancha'],
    ['Pop-corn', 'Chips'],
    ['Glace', 'Sorbet'],
    ['Tiramisu', 'Fondant au chocolat'],
    ['Paella', 'Couscous'],
    ['Nutella', 'Confiture'],
    ['Pizza', 'Quiche'],
    ['Lasagnes', 'Gratin dauphinois'],
    ['Nuggets', 'Tenders'],
    ['Pancakes', 'Pain perdu'],
    ['Ramen', 'Pho'],
    ['Cookie', 'Brownie'],
    ['Saucisson', 'Chorizo'],
    ['Mozzarella', 'Burrata'],
    ['Fraise', 'Framboise'],

    // Boissons
    ['Mojito', 'Spritz'],
    ['Champagne', 'Prosecco'],
    ['Bière', 'Cidre'],
    ['Red Bull', 'Monster'],
    ['Ice Tea', 'Oasis'],
    ['Expresso', 'Cappuccino'],
    ['Bubble tea', 'Smoothie'],
    ['Vodka', 'Tequila'],
    ['Jägermeister', 'Get 27'],
    ['Rosé', 'Vin blanc'],
    ['Pastis', 'Limoncello'],
    ['Sangria', 'Punch'],

    // Enseignes & applis
    ['McDo', 'Burger King'],
    ['Uber Eats', 'Deliveroo'],
    ['Lidl', 'Aldi'],
    ['Ikea', 'Action'],
    ['Zara', 'H&M'],
    ['Vinted', 'Leboncoin'],
    ['Amazon', 'AliExpress'],
    ['Netflix', 'Prime Video'],
    ['Spotify', 'Deezer'],
    ['Instagram', 'TikTok'],
    ['Snapchat', 'WhatsApp'],
    ['Tinder', 'Hinge'],
    ['Twitch', 'YouTube'],
    ['Lydia', 'PayPal'],
    ['ChatGPT', 'Google'],
    ['Waze', 'Google Maps'],
    ['Sephora', 'Nocibé'],
    ['Decathlon', 'Intersport'],
    ['Ryanair', 'EasyJet'],
    ['BlaBlaCar', 'Flixbus'],
    ['Airbnb', 'Hôtel'],

    // Voyages & lieux
    ['Ibiza', 'Mykonos'],
    ['Barcelone', 'Lisbonne'],
    ['New York', 'Los Angeles'],
    ['Marseille', 'Nice'],
    ['Bali', 'Thaïlande'],
    ['Londres', 'Amsterdam'],
    ['Camping', 'Auberge de jeunesse'],
    ['Plage', 'Lac'],
    ['Festival', 'Concert'],
    ['Boîte de nuit', 'Bar'],
    ['Bowling', 'Billard'],
    ['Escape game', 'Laser game'],
    ['Parc Astérix', 'Disneyland'],
    ['Sauna', 'Hammam'],
    ['Jacuzzi', 'Piscine'],
    ['Métro', 'RER'],
    ['Uber', 'Taxi'],
    ['Bibliothèque', 'Librairie'],
    ['Tour Eiffel', 'Arc de Triomphe'],
    ['Louvre', 'Centre Pompidou'],
    ['Mont-Saint-Michel', 'Château de Versailles'],
    ['Club Med', 'Croisière'],
    ['Ski', 'Snowboard'],
    ['Montagne', 'Campagne'],
    ['Cinéma', 'Théâtre'],

    // Vie étudiante & adulte
    ['Coloc', 'Studio'],
    ['Fac', 'École de commerce'],
    ['Erasmus', 'Stage à l’étranger'],
    ['Stage', 'Alternance'],
    ['CV', 'Lettre de motivation'],
    ['Partiel', 'Rattrapage'],
    ['Entretien d’embauche', 'Premier date'],
    ['Permis', 'Code de la route'],
    ['Livret A', 'Tirelire'],
    ['Loto', 'Casino'],
    ['Bitcoin', 'Lingot d’or'],
    ['Télétravail', 'Open space'],
    ['Lundi matin', 'Dimanche soir'],
    ['Sieste', 'Grasse matinée'],
    ['Gueule de bois', 'Nuit blanche'],
    ['Apéro', 'Pique-nique'],
    ['Crémaillère', 'Anniversaire'],
    ['Mariage', 'EVG'],
    ['Halloween', 'Carnaval'],
    ['Noël', 'Nouvel An'],
    ['Crush', 'Ex'],
    ['Ghosting', 'Râteau'],
    ['Belle-famille', 'Colocataires'],
    ['Végétarien', 'Vegan'],
    ['Régime', 'Jeûne'],
    ['Bronzage', 'Coup de soleil'],

    // Séries, films, jeux
    ['Harry Potter', 'Le Seigneur des anneaux'],
    ['Marvel', 'DC'],
    ['Spider-Man', 'Batman'],
    ['Squid Game', 'La Casa de Papel'],
    ['Friends', 'How I Met Your Mother'],
    ['Game of Thrones', 'Vikings'],
    ['Stranger Things', 'Mercredi'],
    ['Koh-Lanta', 'Pékin Express'],
    ['Les Marseillais', 'Love Island'],
    ['Shrek', 'L’Âge de glace'],
    ['Le Roi Lion', 'Le Livre de la jungle'],
    ['Pokémon', 'Yu-Gi-Oh!'],
    ['Naruto', 'One Piece'],
    ['Titanic', 'Avatar'],
    ['Mario Kart', 'Super Smash Bros'],
    ['FIFA', 'NBA 2K'],
    ['Fortnite', 'Call of Duty'],
    ['Minecraft', 'Roblox'],
    ['PlayStation', 'Xbox'],
    ['Wii', 'Switch'],
    ['Game Boy', 'Nintendo DS'],
    ['Among Us', 'Loup-Garou'],
    ['Uno', 'Skyjo'],
    ['Monopoly', 'Cluedo'],
    ['Action ou vérité', 'Je n’ai jamais'],
    ['Karaoké', 'Blind test'],
    ['Lego', 'Playmobil'],
    ['Barbie', 'Bratz'],
    ['Peluche', 'Doudou'],

    // Musique & célébrités
    ['Jul', 'SCH'],
    ['Booba', 'Kaaris'],
    ['Angèle', 'Aya Nakamura'],
    ['Beyoncé', 'Rihanna'],
    ['Taylor Swift', 'Ariana Grande'],
    ['Drake', 'Travis Scott'],
    ['Daft Punk', 'David Guetta'],
    ['Squeezie', 'Mister V'],
    ['Stromae', 'Orelsan'],
    ['Michael Jackson', 'Elvis Presley'],
    ['Elon Musk', 'Mark Zuckerberg'],
    ['Kim Kardashian', 'Paris Hilton'],

    // Sport
    ['PSG', 'OM'],
    ['Real Madrid', 'Barça'],
    ['Mbappé', 'Griezmann'],
    ['Messi', 'Ronaldo'],
    ['Roland-Garros', 'Wimbledon'],
    ['Formule 1', 'MotoGP'],
    ['Rugby', 'Foot américain'],
    ['Ligue des champions', 'Coupe du monde'],
    ['Basket', 'Handball'],
    ['Padel', 'Tennis'],
    ['Surf', 'Skate'],
    ['Yoga', 'Pilates'],
    ['Boxe', 'MMA'],
    ['Cardio', 'Muscu'],
    ['Basic-Fit', 'CrossFit'],
    ['Marathon', 'Triathlon'],

    // Objets & tech
    ['iPhone', 'Samsung'],
    ['AirPods', 'Casque'],
    ['Chargeur', 'Batterie externe'],
    ['Apple Watch', 'Montre'],
    ['Trottinette électrique', 'Vélib’'],
    ['PowerPoint', 'Excel'],
    ['Wi-Fi', 'Bluetooth'],
    ['Selfie', 'Story'],
    ['Mème', 'GIF'],
    ['Lunettes de soleil', 'Casquette'],
    ['Sneakers', 'Crocs'],
    ['Jogging', 'Jean'],
    ['Doudoune', 'Parka'],
    ['Tatouage', 'Piercing'],
    ['Barbe', 'Moustache'],
    ['Parfum', 'Déodorant'],
    ['Shampooing', 'Gel douche'],
    ['Canapé', 'Lit'],
    ['Sac à dos', 'Valise'],
    ['Polaroid', 'Appareil photo jetable'],
    ['Enceinte Bluetooth', 'Platine vinyle'],

    // Animaux & imaginaire
    ['Requin', 'Dauphin'],
    ['Loup', 'Renard'],
    ['Pingouin', 'Manchot'],
    ['Lion', 'Tigre'],
    ['Hamster', 'Cochon d’Inde'],
    ['Abeille', 'Guêpe'],
    ['Moustique', 'Mouche'],
    ['Licorne', 'Dragon'],
    ['Vampire', 'Zombie'],
    ['Pirate', 'Viking'],
    ['Sorcier', 'Magicien'],
    ['Père Noël', 'Petite souris'],
    ['Fantôme', 'Extraterrestre'],

    // Métiers & divers
    ['Police', 'Gendarmerie'],
    ['Médecin', 'Pharmacien'],
    ['Avocat', 'Juge'],
    ['Astronaute', 'Pilote'],
    ['Influenceur', 'Youtubeur'],
    ['Lune', 'Mars'],
    ['Orage', 'Tempête'],
  ];
  if (typeof module !== 'undefined' && module.exports) module.exports = WORDS;
  else root.WORDS = WORDS;
})(this);
